[package]
name = "pegasus-server"
version = "0.1.0"
authors = ["Simono il magnifico <simoneromano@tutanota.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# HTTP Server
actix-web = "3.3.2"
# Graphql implementation
async-graphql = "2.5.8"
# actix-web graphql adapter
async-graphql-actix-web = "2.5.8"
# Hashers
djangohashers = { version = "1.4.0", default-features = false, features = ["with_argon2"] }
# Cursors traits
futures = "0.3.13"
# Serialize/Deserializer
serde = { version = "1.0.123", features = ["derive"] }
thiserror = "1.0.24"
# serde_derive = "1.0.123"
# MongoDB ODM
wither = "0.9.0"
