version: "3.6"

services: 
  mongodb:
    image: mongodb
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes: 
      - mongo_data:/data/db

volumes: 
  mongo_data:
